tunnel: 10451b71-bfe3-4176-a5f7-27c8b5e5b61b
no-autoupdate: true
protocol: auto
loglevel: debug  # Changed to debug for troubleshooting
metrics: 0.0.0.0:2000

ingress:
  - hostname: n8n.virtualxperiencellc.com
    service: http://n8n:5678
    originRequest:
      connectTimeout: 60s
      httpHostHeader: n8n.virtualxperiencellc.com
      noTLSVerify: true
  - service: http_status:404